'use strict';

const DASHBOARD_KEY='mat_executive_dashboard_v1';
const HISTORY_KEY='mat_executive_dashboard_history_v1';
const THEME_KEY='mat_dashboard_theme';
const state={payload:null,filtered:[],history:[],view:'overview'};
const $=id=>document.getElementById(id);
const text=value=>String(value??'');
const escapeHtml=value=>text(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const number = (value) => value !== null && value !== undefined && value !== '' && Number.isFinite(Number(value)) ? Number(value) : null;
const formatDate=value=>value?new Date(value).toLocaleDateString('pt-BR'):'Não identificada';
const formatDateTime=value=>value?new Date(value).toLocaleString('pt-BR'):'Não identificada';
const average=values=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;
const sum=(courses,key)=>courses.reduce((total,course)=>total+(number(course[key])||0),0);

function readingStatus(course){if(number(course.errors)>0)return'Parcial';if(number(course.unverified)>0)return'Conferir';if(course.totalPending===null||course.totalPending===undefined)return'Não coletada';return'Concluída';}
function metric(label,value,detail='',danger=false){return`<article class="metric${danger?' danger':''}"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong>${detail?`<small>${escapeHtml(detail)}</small>`:''}</article>`;}
function quality(label,value,detail){return`<article class="quality"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong><small>${escapeHtml(detail)}</small></article>`;}
function viewHead(title,description,action=''){return`<header class="view-head"><div><h2>${escapeHtml(title)}</h2><p>${escapeHtml(description)}</p></div>${action}</header>`;}
function empty(message){return`<div class="empty">${escapeHtml(message)}</div>`;}

function applyFilters(){
  const environment=$('filter-environment').value,vigency=$('filter-vigency').value,status=$('filter-status').value,query=$('filter-search').value.trim().toLowerCase();
  state.filtered=state.payload.courses.filter(course=>{
    if(environment&&course.environment!==environment)return false;
    if(vigency&&course.vigency!==vigency)return false;
    const reading=readingStatus(course);
    if(status==='pending'&&!(number(course.totalPending)>0))return false;
    if(status==='clear'&&!(number(course.totalPending)===0&&reading==='Concluída'))return false;
    if(status==='review'&&reading==='Concluída')return false;
    return !query||`${course.groupName} ${course.name} ${course.courseId}`.toLowerCase().includes(query);
  });
  renderView();
}

function courseTable(courses=state.filtered){
  const rows=courses.map(course=>{const reading=readingStatus(course),pending=number(course.totalPending),completion=number(course.completionPercentage),rowClass=pending>0?'pending':reading!=='Concluída'?'review':'';return`<tr class="${rowClass}"><td>${escapeHtml(course.groupName||'Não identificada')}</td><td><a href="${escapeHtml(course.url)}" target="_blank">${escapeHtml(course.name)}</a><br><small>ID ${escapeHtml(course.courseId)}</small></td><td>${escapeHtml(course.vigencyLabel||course.vigency)}</td><td>${escapeHtml(formatDate(course.startsAt))} a ${escapeHtml(formatDate(course.endsAt))}</td><td>${completion===null?'Não coletada':`${completion}%`}</td><td>${number(course.studentCount)??'Não coletado'}</td><td>${number(course.classAverage)??'Não coletada'}</td><td class="${pending>0?'status-red':pending===0?'status-green':'status-amber'}">${pending===null?'Não coletada':pending}</td><td>${escapeHtml(reading)}</td></tr>`;}).join('');
  return`<div class="table-wrap"><table><thead><tr><th>Turma</th><th>UC ou curso</th><th>Vigência</th><th>Período</th><th>Conclusão</th><th>Alunos</th><th>Média</th><th>Pendências</th><th>Leitura</th></tr></thead><tbody>${rows||'<tr><td colspan="9">Nenhum registro corresponde aos filtros.</td></tr>'}</tbody></table></div>`;
}

function overview(){
  const courses=state.filtered,pending=sum(courses,'totalPending'),current=courses.filter(c=>c.vigency==='current').length,future=courses.filter(c=>c.vigency==='future').length,students=courses.map(c=>number(c.studentCount)).filter(v=>v!==null),completion=courses.map(c=>number(c.completionPercentage)).filter(v=>v!==null),grades=courses.map(c=>number(c.classAverage)).filter(v=>v!==null),verified=courses.filter(c=>readingStatus(c)==='Concluída').length,affected=courses.filter(c=>number(c.totalPending)>0).length;
  const top=[...courses].filter(c=>number(c.totalPending)>0).sort((a,b)=>number(b.totalPending)-number(a.totalPending)).slice(0,8);
  return viewHead('Visão geral','Indicadores consolidados das turmas e UCs reconhecidas no Moodle.')+`<section class="metrics">${metric('Cursos e UCs',courses.length)}${metric('UCs atuais',current)}${metric('Turmas futuras',future)}${metric('Alunos identificados',students.length?students.reduce((a,b)=>a+b,0):'Não coletado',students.length?`${students.length} registro(s) com fonte`:'Fonte não exposta')}${metric('Pendências',pending,`${affected} UC(s) com ação`,pending>0)}</section><section class="panel"><div class="panel-head"><div><h3>Conclusão e desempenho</h3><p>Somente fontes reconhecidas entram nos cálculos.</p></div></div><div class="quality-grid">${quality('Conclusão média',completion.length?`${average(completion).toFixed(1)}%`:'Não coletada',`${completion.length} UC(s) com rastreamento`)}${quality('Média das turmas',grades.length?average(grades).toFixed(1):'Não coletada',`${grades.length} turma(s) com média`)}${quality('Cobertura da leitura',courses.length?`${Math.round(verified/courses.length*100)}%`:'0%',`${verified} de ${courses.length} concluída(s)`)}${quality('Turmas com pendências',affected,`${pending} correção(ões) confirmada(s)`)}</div></section><section class="panel"><div class="panel-head"><div><h3>Maiores filas de correção</h3><p>Priorize as UCs com maior volume confirmado.</p></div></div><div class="chart-list">${top.length?top.map(c=>`<div class="chart-row"><span>${escapeHtml(c.name)}</span><div class="bar danger"><span style="width:${Math.max(4,number(c.totalPending)/Math.max(...top.map(x=>number(x.totalPending)))*100)}%"></span></div><strong>${number(c.totalPending)}</strong></div>`).join(''):empty('Nenhuma pendência confirmada nos filtros atuais.')}</div></section>`;
}

function courses(){return viewHead('Turmas e UCs',`${state.filtered.length} registro(s) após os filtros globais.`)+`<section class="panel">${courseTable()}</section>`;}
function risk(){
  const atRisk=state.filtered.filter(c=>number(c.totalPending)>0||readingStatus(c)!=='Concluída').sort((a,b)=>(number(b.totalPending)||0)-(number(a.totalPending)||0));
  return viewHead('Alunos em risco','Triagem por UC. Dados individuais só aparecem quando o Moodle fornece uma fonte nominal segura.')+`<p class="notice info">A coleta atual é agregada e não persiste nomes de estudantes. Pendências e baixa conclusão sinalizam UCs que exigem abertura no Moodle para análise individual.</p><section class="metrics">${metric('UCs para acompanhamento',atRisk.length)}${metric('Pendências confirmadas',sum(atRisk,'totalPending'),'Itens aguardando avaliação',sum(atRisk,'totalPending')>0)}${metric('Leituras incompletas',atRisk.filter(c=>readingStatus(c)!=='Concluída').length)}${metric('Alunos nominais','Não coletados','Proteção de dados por padrão')}</section><section class="panel"><div class="panel-head"><div><h3>Prioridades de acompanhamento</h3><p>Ordenadas por pendências confirmadas.</p></div></div>${courseTable(atRisk)}</section>`;
}
function performance(){
  const measured=state.filtered.filter(c=>number(c.completionPercentage)!==null||number(c.classAverage)!==null).sort((a,b)=>(number(a.completionPercentage)??101)-(number(b.completionPercentage)??101));
  return viewHead('Notas e desempenho','Conclusão de atividades e média da turma são indicadores separados.')+`<p class="notice info">Conclusão mede atividades marcadas como concluídas. Média mede notas quando a página do curso expõe esse valor. A ausência de uma fonte aparece como “não coletada”.</p><section class="panel"><div class="panel-head"><div><h3>Conclusão por UC</h3><p>${measured.length} UC(s) com pelo menos uma métrica reconhecida.</p></div></div><div class="chart-list">${measured.length?measured.map(c=>{const v=number(c.completionPercentage);return`<div class="chart-row"><span>${escapeHtml(c.name)}</span><div class="bar"><span style="width:${v??0}%"></span></div><strong>${v===null?'N/D':`${v}%`}</strong></div>`;}).join(''):empty('O Moodle ainda não forneceu métricas de conclusão ou média.')}</div></section>`;
}
function tutors(){return viewHead('Tutores e monitores','Cobertura operacional por responsável.')+`<p class="notice">Os cartões da página inicial não fornecem uma identificação confiável e padronizada do tutor em todos os ambientes. A Central não atribui cursos a pessoas sem uma fonte verificável.</p><section class="metrics">${metric('Tutores identificados','Não coletado')}${metric('Cursos sem responsável','Não verificável')}${metric('Carga média por tutor','Não calculável')}</section><section class="panel">${empty('Quando o Moodle expuser o responsável no inventário, esta área mostrará carga de turmas, pendências e cobertura por tutor.')}</section>`;}
function calendar(){const future=state.filtered.filter(c=>c.vigency==='future'&&c.startsAt).sort((a,b)=>a.startsAt-b.startsAt);return viewHead('Calendário de futuras turmas','Cursos e UCs ordenados pela data de início reconhecida.')+`<div class="calendar-grid">${future.length?future.map(c=>`<article class="calendar-card"><time datetime="${new Date(c.startsAt).toISOString()}">${escapeHtml(formatDate(c.startsAt))}${c.endsAt?` a ${escapeHtml(formatDate(c.endsAt))}`:''}</time><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.groupName||'Turma não identificada')}</p><a href="${escapeHtml(c.url)}" target="_blank">Abrir no Moodle</a></article>`).join(''):empty('Nenhuma turma futura com data reconhecida corresponde aos filtros.')}</div>`;}
function queue(){const queue=state.filtered.map(c=>({...c,priority:(number(c.totalPending)||0)*10+(readingStatus(c)==='Parcial'?5:readingStatus(c)==='Conferir'?3:0)})).filter(c=>c.priority>0).sort((a,b)=>b.priority-a.priority);return viewHead('Fila de trabalho','Priorização por volume de pendências e integridade da leitura.')+`<section class="panel"><div class="table-wrap"><table><thead><tr><th>Prioridade</th><th>Turma</th><th>UC</th><th>Pendências</th><th>Leitura</th><th>Ação</th></tr></thead><tbody>${queue.map((c,i)=>`<tr class="${number(c.totalPending)>0?'pending':'review'}"><td><span class="badge ${i<3?'red':''}">${i+1}</span></td><td>${escapeHtml(c.groupName||'Não identificada')}</td><td>${escapeHtml(c.name)}</td><td>${number(c.totalPending)??'Não coletada'}</td><td>${escapeHtml(readingStatus(c))}</td><td><a href="${escapeHtml(c.url)}" target="_blank">Abrir UC</a></td></tr>`).join('')||'<tr><td colspan="6">Nenhuma ação pendente nos filtros atuais.</td></tr>'}</tbody></table></div></section>`;}
function environments(){const groups=Object.groupBy?Object.groupBy(state.filtered,c=>c.environment||'Não identificado'):state.filtered.reduce((acc,c)=>((acc[c.environment||'Não identificado']??=[]).push(c),acc),{});return viewHead('Comparativo de ambientes','Cobertura e pendências por domínio Moodle.')+`<section class="metrics">${Object.entries(groups).map(([name,courses])=>metric(name,courses.length,`${sum(courses,'totalPending')} pendência(s)`,sum(courses,'totalPending')>0)).join('')||metric('Ambientes',0)}</section><section class="panel">${courseTable()}</section>`;}
function history(){return viewHead('Histórico de análises','Snapshots locais, limitados às 24 atualizações mais recentes.')+`<section class="panel"><div class="stack">${state.history.length?state.history.map(item=>`<div class="snapshot"><strong>${escapeHtml(formatDateTime(item.generatedAt))}</strong><span>${item.courseCount} cursos/UCs</span><span>${item.currentCount} atuais</span><span>${item.pendingCount} pendências</span><span>${item.partial?'Inventário parcial':'Inventário integral'}</span></div>`).join(''):empty('Ainda não existe histórico suficiente.')}</div></section>`;}
function reports(){return viewHead('Central de relatórios','Exporte exatamente o conjunto resultante dos filtros globais.')+`<div class="report-grid"><article class="report-card"><h3>Relatório geral CSV</h3><p>Dados tabulares de turmas, períodos, conclusão, média e pendências.</p><button data-export="csv" type="button">Baixar CSV</button></article><article class="report-card"><h3>Calendário CSV</h3><p>Somente turmas e UCs futuras, ordenadas pela data de início.</p><button data-export="calendar" type="button">Baixar calendário</button></article><article class="report-card"><h3>Fila de trabalho CSV</h3><p>UCs com pendências ou leitura que exige conferência.</p><button data-export="queue" type="button">Baixar fila</button></article><article class="report-card"><h3>Relatório PDF</h3><p>Abre a impressão do navegador para salvar a visão atual em PDF.</p><button data-export="pdf" type="button">Exportar PDF</button></article><article class="report-card"><h3>Backup JSON</h3><p>Snapshot técnico completo para auditoria ou recuperação local.</p><button data-export="json" type="button">Baixar JSON</button></article></div>`;}

const views={overview,courses,risk,performance,tutors,calendar,queue,environments,history,reports};
function renderView(){const root=$('view-root');root.innerHTML=(views[state.view]||overview)();root.querySelectorAll('[data-export]').forEach(button=>button.addEventListener('click',()=>exportReport(button.dataset.export)));}
function csvCell(value){const raw=text(value),safe=/^[\s]*[=+\-@]/.test(raw)?`'${raw}`:raw;return`"${safe.replace(/"/g,'""')}"`;}
function download(content,type,name){const url=URL.createObjectURL(new Blob([content],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportReport(type){
  if(type==='pdf'){window.print();return;}if(type==='json'){download(JSON.stringify({exportedAt:new Date().toISOString(),filters:{environment:$('filter-environment').value,vigency:$('filter-vigency').value,status:$('filter-status').value,search:$('filter-search').value},courses:state.filtered},null,2),'application/json','central_gestao_moodle.json');return;}
  let courses=state.filtered,headers=['ambiente','turma','curso_id','uc_ou_curso','url','vigencia','inicio','fim','conclusao_percentual','alunos','media_turma','pendencias','atividades_com_pendencias','situacao_leitura'];
  if(type==='calendar')courses=courses.filter(c=>c.vigency==='future').sort((a,b)=>(a.startsAt||0)-(b.startsAt||0));
  if(type==='queue')courses=courses.filter(c=>number(c.totalPending)>0||readingStatus(c)!=='Concluída');
  const rows=courses.map(c=>[c.environment,c.groupName,c.courseId,c.name,c.url,c.vigencyLabel,formatDate(c.startsAt),formatDate(c.endsAt),c.completionPercentage??'',c.studentCount??'',c.classAverage??'',c.totalPending??'',c.activitiesPending??'',readingStatus(c)]),filename=type==='calendar'?'calendario_futuras_turmas.csv':type==='queue'?'fila_de_trabalho.csv':`dashboard_turmas_${new Date().toISOString().slice(0,10)}.csv`;
  download('\ufeff'+[headers,...rows].map(row=>row.map(csvCell).join(';')).join('\n'),'text/csv;charset=utf-8',filename);
}
async function saveSnapshot(){const courses=state.payload.courses,snapshot={generatedAt:state.payload.generatedAt||new Date().toISOString(),courseCount:courses.length,currentCount:courses.filter(c=>c.vigency==='current').length,pendingCount:sum(courses,'totalPending'),partial:Boolean(state.payload.inventoryPartial)};if(!state.history.some(item=>item.generatedAt===snapshot.generatedAt)){state.history=[snapshot,...state.history].slice(0,24);await chrome.storage.local.set({[HISTORY_KEY]:state.history});}}
async function initialize(){
  const data=await chrome.storage.local.get([DASHBOARD_KEY,HISTORY_KEY,THEME_KEY]);state.payload=data[DASHBOARD_KEY]||{courses:[],generatedAt:null,inventoryPartial:true};state.history=Array.isArray(data[HISTORY_KEY])?data[HISTORY_KEY]:[];state.filtered=state.payload.courses;document.documentElement.dataset.theme=data[THEME_KEY]||'light';$('generated-at').textContent=state.payload.generatedAt?`Dados atualizados em ${formatDateTime(state.payload.generatedAt)}`:'Nenhum dado agregado foi recebido.';$('partial-warning').hidden=!state.payload.inventoryPartial;
  [...new Set(state.payload.courses.map(c=>c.environment).filter(Boolean))].sort().forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;$('filter-environment').appendChild(option);});
  ['filter-environment','filter-vigency','filter-status'].forEach(id=>$(id).addEventListener('change',applyFilters));$('filter-search').addEventListener('input',applyFilters);
  document.querySelectorAll('.nav-item').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(item=>{item.classList.toggle('is-active',item===button);item.removeAttribute('aria-current');});button.setAttribute('aria-current','page');state.view=button.dataset.view;renderView();$('view-root').focus();}));
  $('theme-toggle').addEventListener('click',async()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;await chrome.storage.local.set({[THEME_KEY]:theme});});
  $('refresh-source').addEventListener('click',()=>{const host=state.payload.courses.find(c=>c.environment)?.environment;if(host)window.open(`https://${host}/my/`,'_blank','noopener');});
  await saveSnapshot();renderView();
}
initialize();
